### ISSUE TITLE
Microsoft.Quantum.IQSharp.Snippets[0] unknown syntax in backend process circuit

### ISSUE THREAD

**Issue by cqc-melf** [CQCL/pytket-qsharp#37]
See https://github.com/CQCL/pytket-qsharp/actions/runs/4574675242 and https://github.com/CQCL/pytket/actions/runs/4573820401/jobs/8075469293

.fail: Microsoft.Quantum.IQSharp.Snippets[0]
      QS3001 (/snippet_.qs:Microsoft.VisualStudio.LanguageServer.Protocol.Range): Syntax does not match any known patterns.
No such magic command %estimate.
Possibly similar magic commands:
- %simulate
- %trace
- %lsmagic
To get a list of all available magic commands, run %lsmagic, or visit [https://docs.microsoft.com/qsharp/api/iqsharp-magic/.](https://docs.microsoft.com/qsharp/api/iqsharp-magic/)
Traceback (most recent call last):
/snippet_.qs(5,17): warning QS3308: Deprecated syntax. Use [] to construct an empty array, or [x, size = n] to construct an array of x repeated n times.
  File "/home/runner/work/pytket/pytket/examples/python/comparing_simulators.py", line 258, in <module>
    handle = backend.process_circuit(c, n_shots=10)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/pytket/backends/backend.py", line 256, in process_circuit
    return self.process_circuits(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/pytket/extensions/qsharp/backends/common.py", line 202, in process_circuits
    results = self._calculate_results(qc, n_shots)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/pytket/extensions/qsharp/backends/estimator.py", line 35, in _calculate_results
    results = qscall.estimate_resources()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/qsharp/loader.py", line 111, in estimate_resources
    return qsharp.client.estimate(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/qsharp/clients/iqsharp.py", line 199, in estimate
    for row in raw_counts:
TypeError: 'NoneType' object is not iterable
Counter({(): 10})
/snippet_.qs(5,17): warning QS3308: Deprecated syntax. Use [] to construct an empty array, or [x, size = n] to construct an array of x repeated n times.
Error: Process completed with exit code 1.

**Comment by cqc-melf** [comment]
If you run into this: try `pip install pytket-qsharp==0.34.0rc0`
